name: fishbowl-dev
services:
  database:
    image: postgres:17.0-alpine3.20
    container_name: fishbowl-dev-database
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  pgdata:
